import { ISvg } from "@/types/types";
import logo_footer from "@/assets/svg/footer-logo.svg fill.svg";
import youtube from "@/assets/svg/youtube_footer.svg fill.svg";
import fb from "@/assets/svg/facebook.svg fill.svg";
import insta from "@/assets/svg/instagram.svg fill.svg";
import tt from "@/assets/svg/tiktok.svg fill.svg";
import lin from "@/assets/svg/linked.svg fill.svg";
import tg from "@/assets/svg/telegram.svg fill.svg";
import mail from "@/assets/svg/email.svg fill.svg";
import logo from "@/assets/Logo.svg";
import arrowGreen from "@/assets/svg/arrowTopRightGreen.svg";
import starString from "@/assets/svg/starForString.svg";
import profile from "@/assets/svg/profile.svg";
import coaching from "@/assets/svg/coaching.svg";
import video from "@/assets/svg/video.svg";
import edit from "@/assets/svg/edit.svg";
import settings from "@/assets/svg/settings.svg";
import pro from "@/assets/svg/pro.svg";
import logout from "@/assets/svg/logout.svg";
import arrdown from "@/assets/svg/chevron-down.svg";
import male from "@/assets/svg/male.svg";
import female from "@/assets/svg/female.svg";
import arrow_right from "@/assets/svg/arrow_right.svg";
import check from "@/assets/svg/circle-check.svg";
import win from "@/assets/svg/winner.svg";
import close from "@/assets/svg/close.svg";

export const LogoFooterSvg = logo_footer as ISvg;
export const YoutubeSvg = youtube as ISvg;
export const FaceBookSvg = fb as ISvg;
export const InstagramSvg = insta as ISvg;
export const TikTokSvg = tt as ISvg;
export const LinkedInSvg = lin as ISvg;
export const TelegramSvg = tg as ISvg;
export const EmailSvg = mail as ISvg;
export const LogoSvg = logo as ISvg;

export const ProfileSvg = profile as ISvg;
export const CoachingSvg = coaching as ISvg;
export const WorkoutsSvg = video as ISvg;
export const EditSvg = edit as ISvg;
export const SettingsSvg = settings as ISvg;
export const ProSvg = pro as ISvg;
export const LogoutSvg = logout as ISvg;
export const ArrowTopRightGreen = arrowGreen as ISvg;
export const StarForString = starString as ISvg;
export const ArrowDown = arrdown as ISvg;
export const MaleIco = male as ISvg;
export const FemaleIco = female as ISvg;
export const ArrowRightIco = arrow_right as ISvg;
export const CircleCheckIco = check as ISvg;
export const WinnerIco = win as ISvg;
export const CloseIco = close as ISvg;
